import { StyleSheet } from 'react-native';

export const MENU = [
  { label: 'Dashboard', key: 'dashboard', badge: null, icon: 'home' },
  { label: 'Academias', key: 'academias', badge: null, icon: 'briefcase' },
];

export const KPI = [
  { title: 'Welcome back, Chris!', subtitle: 'Appstack Dashboard', delta: null, icon: 'activity' },
  { title: '$ 24,300', subtitle: 'Pending Orders', delta: '+9', icon: 'mail' },
  { title: '$ 18,700', subtitle: 'Total Revenue', delta: '+9.5%', icon: 'file-text' },
];

export const BAR_VALUES = [72, 78, 40, 58, 66, 52, 70, 62, 88, 54, 82, 76];
export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const FEED = [
  { avatar: 'AB', line: 'Ashley Briggs started following Stacie Hall', time: '5 minutes ago', right: '5m' },
  {
    avatar: 'CW',
    line: "Chris Wood posted something on Stacie Hall's timeline",
    note: 'Ehom nuncenas Mazenas tempus, tellus eget condimen torr numctar...',
    time: '11 minutes ago',
    right: '11m',
  },
  { avatar: 'SH', line: 'Stacie Hall posted a new blog', time: '2 hours ago', right: '2h' },
];

export const CAL_DAYS = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'];
export const CAL_NUMS = [
  '1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20',
  '21','22','23','24','25','26','27','28','29','30','1','2','3','4','5',
];

const BORDER = 'rgba(255,255,255,0.12)';
const MUTED = 'rgba(255,255,255,0.65)';

export default StyleSheet.create({
  app: { flex: 1, flexDirection: 'row', backgroundColor: '#0f0f12' },
  sidebar: {
    width: 240,
    backgroundColor: '#111118',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 12,
    borderRightWidth: 1,
    borderRightColor: '#000',
  },
  brand: { alignItems: 'flex-start', gap: 4, marginBottom: 20 },
  logo: { width: 120, height: 40, resizeMode: 'contain' },
  brandSub: { color: MUTED, fontSize: 11, letterSpacing: 3 },
  menu: { gap: 8 },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  menuItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  menuItemActive: { backgroundColor: 'rgba(255,255,255,0.08)' },
  menuText: { color: MUTED, fontWeight: '700', fontSize: 13 },
  menuTextActive: { color: '#fff' },
  badge: {
    backgroundColor: '#f97316',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeText: { color: '#fff', fontWeight: '800', fontSize: 11 },
  main: { flex: 1 },
  topbar: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topTitle: { color: '#2b1a04', fontSize: 22, fontWeight: '900' },
  topSubtitle: { color: '#5b3618', fontSize: 12 },
  topRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 10,
  },
  flag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
  },
  flagText: { fontSize: 14 },
  profileName: { color: '#2b1a04', fontWeight: '800' },
  profileAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f97316',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: { padding: 16, gap: 14 },
  kpiRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  card: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  kpiCard: { flexBasis: '32%', minWidth: 260, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  kpiTitle: { color: '#2b1a04', fontSize: 16, fontWeight: '800' },
  kpiSub: { color: '#5b3618', marginTop: 4 },
  deltaPill: { marginTop: 6, alignSelf: 'flex-start', backgroundColor: '#f97316', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 },
  deltaText: { color: '#fff', fontWeight: '800', fontSize: 12 },
  rowTwo: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 10 },
  chartCard: { flex: 2, minWidth: 320 },
  feedCard: { flex: 1.4, minWidth: 280 },
  cardHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  cardHeadTitle: { color: '#2b1a04', fontWeight: '800' },
  chart: { height: 220, backgroundColor: 'rgba(255,255,255,0.45)', borderRadius: 12, padding: 12, justifyContent: 'space-between' },
  bars: { flexDirection: 'row', alignItems: 'flex-end', gap: 6, flex: 1 },
  bar: { flex: 1, borderRadius: 6, backgroundColor: '#f97316' },
  months: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  monthText: { color: '#5b3618', fontSize: 10 },
  feed: { gap: 10 },
  feedItem: { flexDirection: 'row', gap: 10, paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.06)' },
  feedAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2b1a04',
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedAvatarText: { color: '#f1f5f9', fontWeight: '800' },
  feedLine: { color: '#2b1a04', fontWeight: '700', fontSize: 12 },
  feedNote: { color: '#5b3618', fontSize: 12, marginTop: 2 },
  feedTime: { color: '#5b3618', fontSize: 11 },
  feedRight: { color: '#2b1a04', fontSize: 12 },
  btnGradient: {
    marginTop: 4,
    backgroundColor: '#f97316',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
  },
  btnGradientText: { color: '#fff', fontWeight: '800' },
  rowThree: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 10 },
  calendarCard: { flex: 1, minWidth: 260 },
  donutCard: { flex: 1, minWidth: 220, alignItems: 'center' },
  apptCard: { flex: 1.2, minWidth: 260 },
  calendar: { marginTop: 6 },
  calHeader: { alignItems: 'center', marginBottom: 8 },
  calMonth: { color: '#2b1a04', fontWeight: '800' },
  calGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  calDay: { width: 32, textAlign: 'center', color: '#2b1a04', fontWeight: '700' },
  calNum: { width: 32, textAlign: 'center', color: '#2b1a04' },
  calMuted: { color: '#a16236' },
  donutWrap: { alignItems: 'center', justifyContent: 'center', paddingVertical: 20, width: '100%' },
  donut: { width: 160, height: 160, borderRadius: 80, borderWidth: 16, borderColor: '#f97316', alignItems: 'center', justifyContent: 'center' },
  donutHole: { width: 90, height: 90, borderRadius: 45, backgroundColor: 'rgba(255,255,255,0.6)', alignItems: 'center', justifyContent: 'center' },
  donutValue: { color: '#2b1a04', fontWeight: '900', fontSize: 20 },
  donutMuted: { color: '#5b3618', fontSize: 12 },
  apptList: { gap: 12 },
  apptRow: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  apptDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#f97316', marginTop: 5 },
  apptTitle: { color: '#2b1a04', fontWeight: '800' },
  apptDesc: { color: '#5b3618', fontSize: 12, marginTop: 2 },
  acadWrap: { gap: 12 },
  acadHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  acadTitle: { color: '#2b1a04', fontSize: 20, fontWeight: '900' },
  acadSub: { color: '#5b3618', fontSize: 12 },
  acadForm: { gap: 12 },
  acadFormTitle: { color: '#2b1a04', fontWeight: '800', fontSize: 15 },
  formGroup: { gap: 6 },
  formLabel: { color: '#2b1a04', fontWeight: '700', fontSize: 13 },
  formInput: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    padding: 12,
    color: '#0f172a',
  },
  formArea: { height: 90, textAlignVertical: 'top' },
  acadList: { gap: 8 },
  acadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  acadRowTitle: { color: '#2b1a04', fontWeight: '800' },
  acadRowMeta: { color: '#5b3618', fontSize: 12 },
  btnNew: {
    backgroundColor: '#f97316',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  btnNewText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  table: { width: '100%', gap: 4 },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  tableHead: { borderBottomColor: 'rgba(0,0,0,0.2)' },
  tableCell: { color: '#2b1a04', fontSize: 13 },
  tableHeadText: { fontWeight: '800' },
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  btnGhost: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  btnGhostText: { color: '#2b1a04', fontWeight: '700', fontSize: 12 },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
